# Generated by Django 5.2.4 on 2025-07-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
